version: '3.1'
services:
  # Aquí indicamos la imagen web que va a tener odoo
  web:
    image: odoo:16.0
    depends_on:
      - mydb
    volumes:
      - ./addons:/mnt/extra-addons
    ports:
      - "8069:8069" # indicamos que lo vamos a levantar en el puerto 8069
    environment:
      - HOST=mydb # indicamos el nombre del host al que nos vamos a conectar, es decir la base de datos
      - USER=odoo # creamos el usuario de esta base d edatos
      - PASSWORD=myodoo # indicamos la contraseña de este usuario
  mydb: # a continuación indicamos que cliente de base de datos vamos a usar
    image: postgres:15 # en este caso usaremos postgres
    environment:
      - POSTGRES_DB=postgres # indicamos que a la base de datos que nos vamos a conectar dentro del cliente postgres será postgres
      - POSTGRES_PASSWORD=myodoo # la contraseña de postgres será myodoo
      - POSTGRES_USER=odoo # el usuario que emplearemos será odoo
    ports:
      - "5433:5432" # aquí indicamos que docker va a usar el puerto por defecto 5432, peor nosotros accederemos a la base d edatos a través del puerto 5433